### ISSUE TITLE
tp bug

### ISSUE THREAD

**Issue by m4kii420** [DrakePork/RegionTeleport#1]
Hello,

Plugin is amazing BUT whenever I teleport players to a specific location they are looking at South??

**Comment by DrakePork** [comment]
Ah whoops found the problem. Should have a fix out today or tommorow.

**Comment by m4kii420** [comment]
> Ah whoops found the problem. Should have a fix out today or tommorow.

Thank you :)

**Comment by DrakePork** [comment]
Fixed with latest update.
