### ISSUE TITLE
Multiple Spawns

### ISSUE THREAD

**Issue by AshiroKun** [DrakePork/RegionTeleport#5]
Hey great plugin! I just had a cool feature that would be pretty useful if its possible.

But can you add a way so that when players are teleported to a spawn that you set via your plugin, it teleports them to different positions in that area? So instead of it being the exact spawn point that is set, it teleports players to maybe a radius in that area randomly?

I think it would be so useful to add as atm all players within the region gets teleported in one spot and it can get clustered if its a lot of players on the server in that region.

There are 2 ways I can think of that might just work.

1) You make it so that you can set multiple spawn points and u can add it to the command and the plugin automatically calculates where players get teleported to based on the number of spawns set & based on how many players in the region.

2) You make it so that you can set a spawn radius on top of the spawn point and depending on the radius it will teleport the players randomly around that radius.

**Comment by DrakePork** [comment]
I could probably add some sort of radius parameter to the command so players are randomly placed in safe areas inside of that radius in relation to the spawn, like
/regiontp tp region1 spawn1 -r:50 (-s)

**Comment by DrakePork** [comment]
Could probably add both options

**Comment by DrakePork** [comment]
Added support for multiple regions & spawns in the latest update: https://modrinth.com/plugin/regionteleport/version/S5ehRggF
